sudo: required

services:
  - docker

script:
  - printenv
  - echo "Change"
  - docker build -t cgiroua/test-repo .

after_success:
 - "{ test $TRAVIS_PULL_REQUEST = 'false' && test $TRAVIS_BRANCH = 'master' && [[ ! \"$TRAVIS_COMMIT_MESSAGE\" =~ \"--skip-push\" ]]  && docker login -u=\"$DOCKERHUB_USER\" -p=\"$DOCKERHUB_PASS\" && docker push cgiroua/test-repo; } || echo 'Skipping the push'"
