sudo: required

services:
  - docker

env: 
  PUSHING=''

script:
  - 'test $TRAVIS_PULL_REQUEST = ''false'' && test $TRAVIS_BRANCH = ''master'' &&
  [[ ! "$TRAVIS_COMMIT_MESSAGE" =~ "--skip-push" ]]  && export PUSHING=", pushing image"'
  - printenv
  - docker build -t cgiroua/test-repo .

after_success:
  - 'test "$PUSHING" == ", pushing image" && docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS" && docker push cgiroua/test-repo'
