sudo: required

services:
  - docker

before_script:
  - docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"

script:
  #- printenv
  - docker build -t cgiroua/test-repo .

after_success:
 - "{ [[ \"$TRAVIS_BRANCH\" == \"master\" ]] && [[ \"$TRAVIS_COMMIT_MESSAGE\" != *--skip-push* ]] && docker push cgiroua/test-repo; } || echo 'Skipped the docker push'"
